#!/bin/bash

KEYWORD="wallpaper"

wget -O /tmp/wallpaper.jpg -q https://source.unsplash.com/featured/?$KEYWORD,$KEYWORD
gsettings set org.gnome.desktop.background picture-uri file:///tmp/wallpaper.jpg